dist: trusty
language: swift
xcode_workspace: NovelReader.xcworkspace
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
xcode_scheme: NovelReader
script:
- xcodebuild -workspace "NovelReader.xcworkspace" -scheme NovelReader -arch x86_64 -arch i386 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build | xcpretty -c
- sonar-scanner -X
addons:
  sonarcloud:
    organization: ppraveentr-github
    token:
      secure: bugUsvHJpY2EFbJmRAI+GG/VAuFu9F6fNxIbOZIAVwWtYAr06/lyTnOzD5Jdj26g/uZ/xyCvjsnR5STtdIvK7DSyC7gcjdMFYPgZCQoKHVQ2JiNa8TLKh/3iNiwt09B6zuF5m+wP0DiCE3j4x60psvFAdhFUQRxBgrI0Kjxe9X3KZrKtkbf1xtjC9u/728RgDbf8D3APp8zlos6AJw9JirGzaYxYTU6bTYfdzX5ZsNUHKfC32wv3XmHE+o11YitD0IVYYyHgQQtDUPN3W/kC5v47C6JF2m8LNldg50YdYTpGQ9wu6TEyztyUOf3sogDY9U9REV3hrMSu5+lNBVMQwUx5u6JMGfkLwlRFwaQgFAJwdt7HZxs/F7XD+9HPp+hhxsD+smxrE42AlNyUzPk/261hvCJLQ5b3Ad5Rsrl1e/T0pQVM4rSt/0mrTzNT8Ebs4p4qMPInxES4dcUEKYNdr/zQQcqmbQ7XSgXtr8vfGJVXJDQlejrdFAZ0T6+/j3uW1DGhWY3N6XL38MvkmbZmmnmHz2VDrCOyJAc57wHlWPPKzixk+mDUrZtDAhlA8/zrP5wM8cdNKmnP24W6KLgSmignzeGWaIPD1xG1G7RwlMpP2Ix5Q9m24wWm9lJHLKP1v8hc0ujIkaGz66I9N4Y6dbJQ1tOQmlLVS4E69QjwsfA=
env:
  global:
    secure: bugUsvHJpY2EFbJmRAI+GG/VAuFu9F6fNxIbOZIAVwWtYAr06/lyTnOzD5Jdj26g/uZ/xyCvjsnR5STtdIvK7DSyC7gcjdMFYPgZCQoKHVQ2JiNa8TLKh/3iNiwt09B6zuF5m+wP0DiCE3j4x60psvFAdhFUQRxBgrI0Kjxe9X3KZrKtkbf1xtjC9u/728RgDbf8D3APp8zlos6AJw9JirGzaYxYTU6bTYfdzX5ZsNUHKfC32wv3XmHE+o11YitD0IVYYyHgQQtDUPN3W/kC5v47C6JF2m8LNldg50YdYTpGQ9wu6TEyztyUOf3sogDY9U9REV3hrMSu5+lNBVMQwUx5u6JMGfkLwlRFwaQgFAJwdt7HZxs/F7XD+9HPp+hhxsD+smxrE42AlNyUzPk/261hvCJLQ5b3Ad5Rsrl1e/T0pQVM4rSt/0mrTzNT8Ebs4p4qMPInxES4dcUEKYNdr/zQQcqmbQ7XSgXtr8vfGJVXJDQlejrdFAZ0T6+/j3uW1DGhWY3N6XL38MvkmbZmmnmHz2VDrCOyJAc57wHlWPPKzixk+mDUrZtDAhlA8/zrP5wM8cdNKmnP24W6KLgSmignzeGWaIPD1xG1G7RwlMpP2Ix5Q9m24wWm9lJHLKP1v8hc0ujIkaGz66I9N4Y6dbJQ1tOQmlLVS4E69QjwsfA=
